export {default as RightArrow} from './right-arrow.svg';
export {default as HomeIcon} from './home.svg';
export {default as ChatIcon} from './chat.svg';
// export {default as ScheduleIcon} from './schedule.svg';
export {default as ScheduleIcon} from './schedule';
export {default as UserIcon} from './user.svg';
export {default as Prev} from './prev.svg';
export {default as Next} from './next.svg';
export {default as Check} from './check.svg';
export {default as SortDown} from './sort-down.svg';
export {default as Plus} from './plus.svg';
